name: Create Release

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on: [workflow_dispatch] # Only manually build release
jobs:
  build-release:
    name: Create Release
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./app
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.7.5"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Build Flutter App Bundle Release
        run: make action-build-appbundle

      - name: Build Flutter APK Release
        run: make action-build-apk
      
      - name: Upload Flutter Bundle Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/src/build/app/outputs/bundle/release
          asset_name: app-release.aab

      - name: Upload Flutter APK Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/src/build/app/outputs/flutter-apk
          asset_name: app-release.apk
