# This is a basic workflow to help you get started with Actions
name: Flutter Build

# Controls when the workflow will run
on:
  on: [push, pull_request]
  
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "**/app"
    paths-ignore:
      - "*.md"
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-20.04
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
    run:
      working-directory: ./app
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: $

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: $

      - name: Build Flutter APK
        run: make action-build-apk

      - name: Build Flutter App Bundle
        run: make action-build-appbundle