# This is a basic workflow to help you get started with Actions
name: Flutter Build

# Controls when the workflow will run
on:
  on: [push, pull_request]

  push:
    paths-ignore:
      - '**/network'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-20.04
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
        defaults:
    run:
      working-directory: ./app
    steps:    
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $

      - name: Build APK
        run: make action-build-apk

      - name: Build App Bundle
        run: make action-build-appbundle