# This is a basic workflow to help you get started with Actions
name: Flutter Build

# Controls when the workflow will run
on: 
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "**/app"
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./app
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.7.5"
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Build Flutter App Bundle
        run: make action-build-appbundle

      - name: Build Flutter APK
        run: make action-build-apk